Omitting jsr311-api from the target platform as it causes method errors.
Specifically java.lang.NoSuchMethodError: org.jboss.resteasy.specimpl.BuiltResponse.getHeaders()Ljavax/ws/rs/core/MultivaluedMap;

https://stackoverflow.com/questions/32109914/java-lang-nosuchmethoderror-org-jboss-resteasy-specimpl-builtresponse-getheader